def find_common_values(*lists):
    if not lists:
        return []

    # Convert the first list to a set
    common_values = set(lists[0])

    # Intersect the set with all subsequent lists
    for lst in lists[1:]:
        common_values.intersection_update(lst)

    return list(common_values)


list2018 = [
    "Acervo de livros infanto-juvenis das bibliotecas municipais per capita",
    "Acervo de livros para adultos das bibliotecas municipais per capita",
    "Centros culturais, casas e espaços de cultura",
    "Cinemas",
    "Museus",
    "Salas de show e concerto",
    "Teatros",
    "Equipamentos culturais públicos",
    "Atendimento nas creches municipais",
    "Atendimento nas pré-escolas municipais",
    "Demanda atendida de creche",
    "Tempo de atendimento para vaga em creche",
    "Proporção do número de matrículas no ensino básico (exceto EJA) no total da população em idade escolar (de 0 a 19 anos)",
    "Proporção do número de matrículas no ensino básico em escolas públicas no total de matrículas",
    "Leitos hospitalares",
    "Mortalidade por AIDS",
    "Mortalidade infantil",
    "Mortalidade materna",
    "Tempo de espera para consultas - clínico geral",
    "Tempo de espera para consultas - programa de saúde da família",
    "Acidentes com bicicleta",
    "Acidentes com automóveis",
    "Acidentes com motocicleta",
    "Acidentes de trânsito",
    "Atropelamentos",
    "Mortalidade por doenças do aparelho respiratório",
    "Mortalidade por doenças do aparelho circulatório",
    "Violência contra a mulher - feminicídio",
    "Violência contra a mulher - todas",
    "Violência de racismo e injúria racial",
    "Violência homofóbica e transfóbica",
    "Favelas",
    "Mortes no trânsito",
    "Violência de trânsito",
    "Diferença salarial entre mulheres e homens - serviço"
]

list2019 = [
    "Centros culturais, casas e espaços de cultura",
    "Salas de show e concerto",
    "Teatros",
    "Museus",
    "Cinemas",
    "Proporção de matrículas nas pré-escolas (EMEIs)",
    "Atendimento nas pré-escolas municipais",
    "Matrículas no Ensino Básico em escolas públicas",
    "Leitos hospitalares",
    "Mortalidade por AIDS",
    "Mortalidade infantil",
    "Mortalidade materna",
    "Tempo de espera para consultas - clínico geral",
    "Tempo de espera para consultas - programa de saúde da família",
    "Acidentes com bicicleta",
    "Acidentes com automóveis",
    "Acidentes com motocicleta",
    "Acidentes de trânsito",
    "Atropelamentos",
    "Mortalidade por doenças do aparelho respiratório",
    "Mortalidade por doenças do aparelho circulatório",
    "Violência contra a mulher - feminicídio",
    "Violência contra a mulher - todas",
    "Violência de racismo e injúria racial",
    "Violência homofóbica e transfóbica",
    "Favelas",
    "Mortes no trânsito",
    "Violência de trânsito",
    "Diferença salarial entre mulheres e homens - serviços",
]
list2020 = [
    "População total",
    "População preta e parda",
    "População feminina",
    "População jovem",
    "Acesso a transporte de massa",
    "Viagens por transporte público em relação às viagens motorizadas",
    "Tempo médio das viagens ao trabalho por transporte público",
    "Transferências nas viagens ao trabalho por transporte público",
    "Famílias sem automóvel",
    "Acesso a infraestrutura cicloviária",
    "Acidentes de trânsito",
    "Mortes no trânsito",
    "Violência contra a mulher - todas",
    "Violência contra a mulher - feminicídio",
    "Violência LGBTQIAP+",
    "Violência racial",
    "Homicídio de Jovens",
    "Favelas",
    "Gravidez na adolescência",
    "Mortalidade materna",
    "Mortalidade infantil",
    "Idade média ao morrer",
    "Cobertura da Atenção Básica",
    "Tempo médio para consultas na Atenção Básica",
    "ICSAP – Internações por Condições Sensíveis à Atenção Primária",
    "Mortalidade por doenças do aparelho circulatório",
    "Mortalidade por doenças do aparelho respiratório",
    "Mortalidade por neoplasias do aparelho digestivo",
    "Tempo de atendimento para vaga em creche",
    "Matrículas no Ensino Básico em escolas públicas",
    "Adequação da formação docente no Ensino Fundamental da rede pública",
    "Índice do Nível Socioeconômico das Escolas (INSE)",
    "Evasão escolar no Ensino Fundamental da rede municipal",
    "Equipamentos públicos de cultura",
    "Centros culturais, casas e espaços de cultura",
    "Museus",
    "Salas de show e concerto",
    "Cinemas",
    "Teatros",
    "Acervo de livros para adultos",
    "Acervo de livros infanto-juvenis",
    "Ocupações Culturais",
    "Equipamentos públicos de esporte",
    "Oferta de emprego formal",
    "Remuneração média mensal do emprego formal",
    "Renda média familiar mensal",
]
list2021 = [
    "População total",
    "População preta e parda",
    "População feminina",
    "População Infantil",
    "População jovem",
    "Densidade domiciliar",
    "Favelas",
    "Oferta de emprego formal",
    "Remuneração média mensal do emprego formal",
    "Proporção de Imposto sobre serviço (ISS) arrecadado",
    "Acesso a transporte de massa",
    "Acesso a infraestrutura cicloviária",
    "Ocorrências de trânsito",
    "Mortes no trânsito",
    "Acesso internet - Mapeamento das antenas (área/km²)",
    "Acesso internet - Mapeamento das antenas (População distrito)",
    "Violência contra a mulher - todas",
    "Violência contra a mulher - feminicídio",
    "Violência LGBTQIAP+",
    "Violência racial",
    "Homicídios de jovens",
    "Agressões por intervenção policial",
    "Mortes por intervenção policial",
    "Idade média ao morrer",
    "Mortalidade por Covid-19",
    "Gravidez na adolescência",
    "Mortalidade materna",
    "Mortalidade infantil",
    "Mortalidade por doenças do aparelho circulatório",
    "Mortalidade por doenças do aparelho respiratório",
    "Tempo médio para consultas na Atenção Básica",
    "Tempo médio para consultas na Atenção Especializada",
    "Tempo médio para realização de exames especializados",
    "Tempo médio em dias para Consultas com Psiquiatras",
    "ICSAP – Internações por Condições Sensíveis à Atenção Primária",
    "Cobertura estimada - Atenção Básica",
    "Cobertura estimada - ESF",
    "Tempo de atendimento para vaga em creche",
    "Matrículas no Ensino Básico em escolas públicas",
    "Distorção Idade-Série no Ensino Fundamental da rede municipal",
    "Abandono escolar no Ensino Fundamental da rede municipal",
    "Índice do Nível Socioeconômico das Escolas (INSE)",
    "Centros culturais, casas e espaços de cultura",
    "Equipamentos públicos de cultura",
    "Cinemas",
    "Museus",
    "Teatros",
    "Espaços culturais independentes",
    "Ocupações culturais",
    "Equipamentos culturais com Wi-Fi",
    "Equipamentos públicos de esporte",
]

list2022 = [
    "População total",
    "População preta e parda",
    "População feminina",
    "População Infantil",
    "População jovem",
    "População em situação de rua",
    "Favelas",
    "Habitações  de Interesse Social (HIS)  Licenciadas",
    "Habitações  de Interesse  Social (HIS) produzidas  por SEHAB",
    "Habitações  de Interesse  Social (HIS)  Licenciadas (até 3 salários mínimos)",
    "Habitações  de Interesse  Social (HIS)  Licenciadas (entre 3 a 6 salários mínimos)",
    "Ocorrências de trânsito",
    "Mortes no trânsito",
    "Tempo médio de  deslocamento por transporte público",
    "Velocidade média ônibus (km/h)",
    "Acesso a transporte de massa",
    "Acesso a infraestrutura cicloviária",
    "Acesso internet - Mapeamento das antenas (População distrito)",
    "Acesso internet - Mapeamento das antenas (área/km²)",
    "Oferta de emprego formal",
    "Remuneração média mensal do emprego formal",
    "Micro Empreendedores Individuais  (MEIs)",
    "Desigualdade salarial  (emprego  formal)",
    "Gravidez na adolescência",
    "Idade média ao morrer",
    "Mortalidade materna",
    "Mortalidade infantil",
    "Tempo médio para consultas na Atenção Básica",
    "Mortalidade por Covid-19",
    "Tempo de atendimento para vaga em creche",
    "Matrículas no Ensino Básico em escolas públicas",
    "Distorção Idade-Série no Ensino Fundamental da rede municipal",
    "Abandono escolar no Ensino Fundamental da rede municipal",
    "Ideb  (Escolas  públicas -  anos iniciais)",
    "Ideb  (Escolas  públicas -  anos finais)",
    "Adequação  da formação docente",
    "Esforço  docente",
    "Centros culturais, casas e espaços de cultura",
    "Equipamentos públicos de cultura",
    "Cinemas",
    "Espaços culturais independentes",
    "Equipamentos públicos de esporte",
    "Quadras esportivas nas escolas públicas",
    "Violência racial",
    "Violência contra a mulher",
    "Violência LGBTQIAP+",
    "Deslocamentos médio para  denúncias de  violência  contra mulher",
    "Feminicídio",
    "Mortes por intervenção policial",
    "Homicídios",
    "Homicídios de jovens",
    "Agressões por intervenção policial",
    "Emissão de poluentes  atmosféricos por área  (kg/km²/dia)",
]

lista2023 = [
    "População total",
    "Remuneração média mensal do emprego formal",
    "Acesso a transporte de massa",
    "Matrículas no ensino básico em escolas públicas",
    "Quadras esportivas nas escolas públicas",
    "Acesso a infraestrutura cicloviária",
    "Cobertura vegetal (%)",
    "Idade média ao morrer",
    "Oferta de emprego formal",
    "População preta e parda",
    "População feminina",
    "População jovem",
    "Acesso internet móvel (População distrito)",
    "Acesso internet móvel (por área/km²)",
    "Espaços culturais independentes",
    "Velocidade média ônibus (km/h)",
    "Equipamentos públicos de cultura",
    "População Infantil",
    "Ideb (Escolas públicas - anos iniciais)",
    "Ideb (Escolas públicas - anos finais)",
    "Pontos de Entrega Vountária (PEV)",
    "Equipamentos públicos de esporte",
    "Desigualdade salarial (emprego formal)",
    "Centros culturais, casas e espaços de cultura",
    "Cinemas",
    "Feminicídio",
    "Homicídios",
    "Homicídios de jovens",
    "Agressões por intervenção policial",
    "Mortes por intervenção policial",
    "Número de áreas contaminadas",
    "Mortes no trânsito",
    "Violência LGBTQIAP+",
    "Violência racial",
    "Famílias em atendimento habitacional provisório por situação de risco e emergência",
    "Favelas",
    "Gravidez na adolescência",
    "Mortalidade materna",
    "Mortalidade infantil",
    "Tempo médio para consultas na atenção básica",
    "Esforço docente",
    "Emissão de poluentes atmosféricos por área (kg/km²/dia)",
    "Abandono escolar no ensino fundamental da rede municipal",
    "População em situação de rua",
    "Deslocamentos médio para denúncias de violência contra mulher",
    "Mortalidade por Covid-19",
    "Adequação da formação docente",
    "Tempo de atendimento para vaga em creche",
    "Distorção idade-série no ensino fundamental da rede municipal",
    "Tempo médio de deslocamento por transporte público",
    "Violência contra a mulher (todas)",
    "Homicídios de jovens",
    "Agressões por intervenção policial",
    "Emissão de poluentes  atmosféricos por área  (kg/km²/dia)",
]
common_values = find_common_values(list2020, list2021, list2022, lista2023)
print(common_values)
